csx773/Cards-Against-the-Internet

- QUESTION.md
- package-lock.json
- react-front-end/package-lock.json
> Added all the questions.

- README.md
- react-front-end/package-lock.json
> Testing init

- README.md
- react-front-end/src/App.js
- react-front-end/src/Card.jsx
> Added card component

- react-front-end/homepage.html
> Finished Homepage layout.

- rails-back-end/db/schema.rb
> Fixed rails schema.rb file.

- react-front-end/src/AnswererDeck.jsx
- react-front-end/src/App.css
- react-front-end/src/Game.jsx
- react-front-end/src/Gameroom.jsx
- react-front-end/src/QuestionerDeck.jsx
Inside the game able to see game theme, Answerer's deck done, css cards with shadow.
> Inside the game able to see game theme, Answerer's deck done, css cards with shadow.

- rails-back-end/db/seeds.rb
- react-front-end/src/AnswerSection.jsx
- react-front-end/src/Game.jsx
- react-front-end/src/Gameroom.jsx
- react-front-end/src/Lobby.jsx
- react-front-end/src/Modals/CreateRoomModal.jsx
> All get route tests to display successfully tested

- react-front-end/src/Banner.jsx
- react-front-end/src/Home.jsx
- react-front-end/src/LobbyNav.jsx
- react-front-end/src/Modals/LoginModal.jsx
- react-front-end/src/Modals/SubmitIdeadModal.jsx
> Created 'share idea pop-up' and some minor fixes.

- react-front-end/src/Lobby.jsx
- react-front-end/src/Modals/CreateRoomModal.jsx
> after the room creation roomCreateModal closes

- react-front-end/src/Game.jsx
minor fixes - now can see max player number
> minor fixes - now can see max player number

- react-front-end/src/Game.jsx
- react-front-end/src/Loader.css
> implement loading circle when game is loading. 

- QUESTION.md
- rails-back-end/db/seeds.rb
- react-front-end/public/index.html
- react-front-end/src/App.js
- react-front-end/src/Chat.jsx
- react-front-end/src/Footer.jsx
- react-front-end/src/Game.jsx
- react-front-end/src/Gameroom.jsx
- react-front-end/src/Home.jsx
- react-front-end/src/Loader.css
- react-front-end/src/css/App.css
- react-front-end/src/index.js
seed all question cards in questions.md and little code clean up for …  …
…App.js, Home.jsx
>  seed all question cards in questions.md and little code clean up for …  … …App.js, Home.jsx

- react-front-end/src/Chat.jsx
- react-front-end/src/QuestionSection.jsx
minor fixes - questionSection.jsx change the back of the cards' title
and link to mail app when user clicks "contact Us" button.
also, score board in out Game.jsx
> minor fixes - questionSection.jsx change the back of the cards' title

- react-front-end/src/Lobby.jsx
enable loading logo for lobby page
and pulled from main, now logout works as well.
>  enable loading logo for lobby page // logout

- react-front-end/src/Gameroom.jsx
- react-front-end/src/Modals/SubmitIdeadModal.jsx
- react-front-end/src/css/App.css
- react-front-end/src/css/login.css
> Login/submit form & lobby(gameroom/settings) are fully responsive at all resolutions now.

- README.md
- rails-back-end/app/controllers/api/games_controller.rb
- react-front-end/package-lock.json
- react-front-end/src/Chat.jsx
- react-front-end/src/Game.jsx
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
> able to see username in scoreboard and 'cannot go in to the room bug' fixed.

- react-front-end/src/LobbyNav.jsx
- react-front-end/src/Nav.jsx
> conditional rendering on Nav.jsx and lobbynav.jsx

- react-front-end/src/Banner.jsx
- react-front-end/src/Modals/LeaderboardModal.jsx
- react-front-end/src/css/App.css
- react-front-end/src/css/submitform.css
> Modified leaderboard 

- rails-back-end/db/seeds.rb
- react-front-end/src/Banner.jsx
- react-front-end/src/Chat.jsx
- react-front-end/src/Game.jsx
- react-front-end/src/QuestionerDeck.jsx
- react-front-end/src/css/App.css
> Added chat feature(states) and modified all css errors

- react-front-end/src/AnswerSection.jsx
- react-front-end/src/css/App.css
> Changed image
